<?php 
/**
 * Http_Header_Simple.php
 * 
 * Notes and Credits 
 *   for https://www.skeptycal.com 
 *
 * PHP version 7
 *
 * LICENSE: MIT
 *
 * @category  Creative_Portfolio
 * @package   Portfolio
 * @author    Michael Treanor  <skeptycal@gmail.com>
 * @copyright 2018 © Michael Treanor
 * @license   MIT <https://opensource.org/licenses/MIT>
 * @version   GIT: 2.20.1
 * @link      https://www.skeptycal.com/index.php
 * PHP 7.3.0 (cli) (built: Dec  7 2018 11:00:11)
 *
 * @tags
 * @phpcs:disable Generid.Files.LineLength.LineLimit = "120"
 */

/*
Note:

The closing tag of a PHP block at the end of a file is optional, and in some cases omitting it is helpful when using include or require, so unwanted whitespace will not occur at the end of files, and you will still be able to add headers to the response later. It is also handy if you use output buffering and would not like to see added unwanted whitespace at the end of the parts generated by the included files.
*/

/*
normalize.js replaced with modern-normalize.js :

https://github.com/sindresorhus/modern-normalize
"All credit should go to normalize.css. I just removed some cruft and 
added some improvements. If you have questions about the source, 
check out the original source: 
<https://github.com/necolas/normalize.css/blame/master/normalize.css>
*/
/*
Background Images
=================

current image:
    https://www.nasa.gov/sites/default/files/images/672309main_M107_full.jpg
    Courtesy of NASA.
    
secondary image: 
    An infrared image showing fledgling stars located in the Orion Nebula. 
    https://www.nasa.gov/multimedia/imagegallery/image_feature_2195.html
    Image credit: NASA Created: 29 February 2012.
                
        Icons and other resources by Rawpixel.com and Ydlabs, among others.
        href="https://www.freepik.com/free-photos-vectors/background"

        Artistic site design inspiration by 
        <a href="https://github.com/saracope">Sara Cope</a>.
*/
?>